name: go

on:
  pull_request:
    paths:
      - .github/workflows/go.yaml
      - go.*
      - main.go
      - pkg/**.go
      - Makefile
  push:
    branches:
      - main
    paths:
      - .github/workflows/go.yaml
      - go.*
      - main.go
      - pkg/**.go
      - Makefile

jobs:
  go:
    uses: int128/kubebuilder-workflows/.github/workflows/go.yaml@v1
    with:
      go-version: 1.19.5
      golangci-lint-version: v1.50.1
