name: manifest

on:
  pull_request:
    branches: [main]
    paths:
      - config/**
      - .github/workflows/manifest.yaml

jobs:
  diff:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: int128/kustomize-action/diff@v1
        with:
          write-individual-files: true
          kustomization: |
            config/default/kustomization.yaml
